---
title: 'Dissertation Analysis: Examining Counterbalance Effects'
author: "Jamiahus Walton"
date: "5/20/2019"
output: html_document
editor_options:
  chunk_output_type: inline
csl: apa.csl
bibliography: bibliography.bib
params:
  # Dependent Variable
  dependent_name_WithSpace: "Time Remaining"
  dependent_name_NoSpace: "TimeRemaining"
  
  # Team
  dependent_team: "timeRemaining_team"
  
  #Individual
  dependent_ind: "timeRemaining_ind"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Tips for formatting in RMarkdown
# Link: https://monashbioinformaticsplatform.github.io/2017-11-16-open-science-training/topics/rmarkdown.html

# Equations
# Link: https://www.calvin.edu/~rpruim/courses/s341/S17/from-class/MathinRmd.html

# Create awesome HTML table with knitr::kableand kableExtra
# LinkL https://haozhu233.github.io/kableExtra/awesome_table_in_html.html

# Examples of how to use the ggrepel package
# Link: https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html#examples

# Packages for data analysis
library(tidyverse)
library(lme4)
library(lmerTest)
library(emmeans)
library(svMisc)
library(MuMIn)
library(modelr)
library(sjstats)
library(robustlmm)
library(ggrepel)
library(knitr)
library(kableExtra)

# Functions used in documents ----
remove_measures_with_given_value <- function(data_set, col_name, value){
  rows_to_move <- which(as.vector(data_set[,col_name]) == value) 
  
  return(data_set[-rows_to_move,])
}

# Factor columns that need it.
re_factor_columns <- function(userData, columnNames){
  factorData <- userData
  for(column in columnNames){
    print(column)
    factorData[,column] <- factor(factorData[,column])
  }
  return(factorData)
}

# Model the data for the team level analysis ----
model_data_Target_Session <- function(df, dependent, model.type, is.team, is.robust){
  
  if(is.team){
    if(model.type == "null" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ 1 + (1|Team)")))
    } else if(model.type == "All"){
      lmer(data = df, as.formula(paste(dependent,"~ Target * SessionOrder + (1|Team)")))
    } else if(model.type == "NoInteraction" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ Target + SessionOrder + (1|Team)")))
    } else if(model.type == "NoInteraction_NoTarget" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ SessionOrder + (1|Team)")))
    } else if(model.type == "NoInteraction_NoSession" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ Target + (1|Team)")))
    } else if(model.type == "null" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ 1 + (1|Team)")))
    } else if(model.type == "All" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ Target * SessionOrder + (1|Team)")))
    } else if(model.type == "NoInteraction" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ Target + SessionOrder + (1|Team)")))
    } else if(model.type == "NoInteraction_NoTarget" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ SessionOrder + (1|Team)")))
    } else if(model.type == "NoInteraction_NoSession" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ Target + (1|Team)")))
    } else{
      stop("Model.type not supported")
    }
  } else {
    # Run this code if individual level model
    if(model.type == "null" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ 1 + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "All" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ Target * SessionOrder + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "NoInteraction" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ Target + SessionOrder + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "NoInteraction_NoTarget" && !is.robust){
      lmer(data = df, as.formula(paste(dependent,"~ SessionOrder + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "NoInteraction_NoSession"){
      lmer(data = df, as.formula(paste(dependent,"~ Target + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "null" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ 1 + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "All" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ Target * SessionOrder + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "NoInteraction" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ Target + SessionOrder + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "NoInteraction_NoTarget" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ SessionOrder + (1|Team) + (1| Player_ID)")))
    } else if(model.type == "NoInteraction_NoSession" && is.robust){
      rlmer(data = df, as.formula(paste(dependent,"~ Target + (1|Team) + (1| Player_ID)")))
    } else{
      stop("Model.type not supported")
    }
  }
}

#Folder locations ----
figure_directory <- "C:\\Users\\jamia\\Box\\TMET2\\DATA TMET2\\Data_And_Calcuations\\Figures"
main_work_directory_name <- "C:\\Users\\jamia\\Box\\TMET2\\DATA TMET2\\Data_And_Calcuations\\Raw Data\\"

database_folder_name <- "Database"
file_name_output <- "team_player_aggragate_stats.csv"
folder_location_database <- paste(main_work_directory_name, database_folder_name, sep = "")
aggregate_folder_location <- paste(folder_location_database,"\\", file_name_output, sep = "") #This will combine the final file name and the desiered folder location

# Read aggregaate data ----
my_aggregate_data <- read.csv(file =  aggregate_folder_location)

clean_aggregate_data_stats <- remove_measures_with_given_value(data_set =  my_aggregate_data, col_name = "Condition", value = "A") # without none condition

# Re factor the columns
columns_to_refactor <- c("SessionOrder", 
                         "Team", 
                         "Player_ID",
                         "Counterbalance_set",
                         "Condition", 
                         "Dominate.Strategy", 
                         "Condition", 
                         "Target",
                         "Confident_team_comm_important_details_quickly")
clean_aggregate_data_stats <- re_factor_columns(clean_aggregate_data_stats, columns_to_refactor)

# What is the N for Teams ----
N_teams <- length(levels(factor(clean_aggregate_data_stats$Team)))

# What is the N for Inds ----
N_ind <- length(levels(factor(clean_aggregate_data_stats$Player_ID) ))

# Team data set ----
team_data <- clean_aggregate_data_stats %>%
  filter(Player == 1)

# Individual data set ----
ind_data <- clean_aggregate_data_stats

```

# Purpose

The purpose of this document is to examine the effect from the counter balance order. 

# `r params$dependent_name_WithSpace` 

## Team

```{r}
setwd(figure_directory)

data_focus_team <- team_data %>%
  select(SessionOrder, Counterbalance_set, Team, params$dependent_team) %>%
  mutate(position_order = rank(.data[[params$dependent_team]], ties.method = "first"))

ggplot(data_focus_team, aes(x = SessionOrder, y = .data[[params$dependent_team]], fill = Team, group = position_order)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid( . ~ Counterbalance_set) +
  guides(fill = FALSE) +
  labs(title = paste(params$dependent_team, " vs. session order, grouped by counterbalance set"), x = "Session Order", y = params$dependent_team_name_WithSpace) +
  ggsave(filename = paste("CounterBalance_", params$dependent_name_WithSpace, "_BySessionOrder_Group_CounterBalanceSet_Team.png", sep = ""))
```

[Content]

```{r}
setwd(figure_directory)

data_focus_team <- team_data %>%
  select(SessionOrder, Counterbalance_set, Team, params$dependent_team) %>%
  mutate(position_order = rank(.data[[params$dependent_team]], ties.method = "first"))

ggplot(data_focus_team, aes(x = Counterbalance_set, y = .data[[params$dependent_team]], fill = Team, group = position_order)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid( . ~ SessionOrder) +
  guides(fill = FALSE) +
  labs(title = paste(params$dependent_team, " vs. counterbalance set, grouped by  session order"), x = "Counter Balance Set", y = params$dependent_name_WithSpace)+
  ggsave(filename = paste("CounterBalance_", params$dependent_name_WithSpace, "_ByCounterBalanceSet_Group_SessionOrder_Team.png", sep = ""))
```

[Content]

```{r}
setwd(figure_directory)

data_focus_team <- team_data %>%
  select(SessionOrder, Counterbalance_set, Team, params$dependent_team) %>%
  # filter(SessionOrder ==4) %>%
  group_by(SessionOrder, Counterbalance_set) %>%
  summarise(average = mean(.data[[params$dependent_team]]),
            n = length(.data[[params$dependent_team]]),
            StEr = sd(.data[[params$dependent_team]]) / sqrt(length(.data[[params$dependent_team]])))

ggplot(data_focus_team, aes(x = SessionOrder, y = average)) +
  geom_point() +
  labs(title = paste("Averages", params$dependent_team, " vs. session order, grouped by counterbalance set")) +
  geom_errorbar(aes(ymin = average - StEr, ymax = average + StEr)) +
  facet_grid(. ~ Counterbalance_set)

data_focus_team
```

[Content]

```{r}
setwd(figure_directory)

data_focus_team <- team_data %>%
  select(SessionOrder, Counterbalance_set, Team, params$dependent_team) %>%
  # filter(SessionOrder ==4) %>%
  group_by(SessionOrder, Counterbalance_set) %>%
  summarise(average = mean(.data[[params$dependent_team]]),
            n = length(.data[[params$dependent_team]]),
            StEr = sd(.data[[params$dependent_team]]) / sqrt(length(.data[[params$dependent_team]])))

ggplot(data_focus_team, aes(x = Counterbalance_set, y = average)) +
  geom_point() +
  labs(title = paste("Averages", params$dependent_team, " vs. session order, grouped by counterbalance set")) +
  geom_errorbar(aes(ymin = average - StEr, ymax = average + StEr)) +
  facet_grid(. ~ SessionOrder)

data_focus_team
```


## Individual

```{r}
setwd(figure_directory)

data_focus_ind <- ind_data %>%
  select(SessionOrder, Counterbalance_set, Player_ID, Team, params$dependent_ind) #%>%
  # filter(SessionOrder == 4) 

ggplot(data_focus_ind, aes(x = SessionOrder, y = .data[[params$dependent_ind]], fill = Player_ID)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid( . ~ Counterbalance_set) +
  guides(fill = FALSE) +
  labs(title = paste(params$dependent_ind, " vs. session order, grouped by counterbalance set"))
```

[Content]

```{r}
setwd(figure_directory)

data_focus_ind <- ind_data %>%
  select(SessionOrder, Counterbalance_set, Player_ID, params$dependent_ind) %>%
  filter(SessionOrder == 4) %>%
  group_by(SessionOrder, Counterbalance_set) %>%
  summarise(average = mean(.data[[params$dependent_ind]]),
            n = length(.data[[params$dependent_ind]]),
            StEr = sd(.data[[params$dependent_ind]]) / sqrt(length(.data[[params$dependent_ind]])))

ggplot(data_focus_ind, aes(x = SessionOrder, y = average)) +
  geom_point() +
  labs(title = paste("Averages", params$dependent_ind, " vs. session order, grouped by counterbalance set")) +
  geom_errorbar(aes(ymin = average - StEr, ymax = average + StEr)) +
  facet_grid(. ~ Counterbalance_set)

data_focus_ind
```

[Content]

